events {
    worker_connections 1024;
}

http {
    upstream authors {
        server 127.0.0.1:3001;
    }
    upstream categories {
        server 127.0.0.1:3002;
    }
    upstream books {
        server 127.0.0.1:3003;
    }

    server {
        listen ${PORT};

        location /api/authors {
            proxy_pass http://authors;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/categories {
            proxy_pass http://categories;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/books {
            proxy_pass http://books;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            add_header Content-Type application/json;
            return 200 '{"status":"ok","gateway":"nginx"}';
        }

        location / {
            root /app/public;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}
