events {
    worker_connections 1024;
}

http {
    upstream authors {
        server authors:3001;
    }
    upstream categories {
        server categories:3002;
    }
    upstream books {
        server books:3003;
    }

    server {
        listen 80;

        location /api/authors {
            proxy_pass http://authors;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/categories {
            proxy_pass http://categories;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/books {
            proxy_pass http://books;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /health {
            content_type application/json;
            return 200 '{"status":"ok","gateway":"nginx"}';
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}
